### ISSUE TITLE
Move BUIlDING.md contents into README.md

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents-dotnet#17]
Can we move the instructions for BUILDING into the main README?

I don't think we need 2 docs and having 1 doc will make things easier across different languages.

**Comment by jskeet** [comment]
I would prefer not to. They are different docs for different audiences. I believe the vast majority of users will be *consuming* the packages associated with this repo, but never needing to know how to build it themselves or regenerate the code from google-cloudevents. I would rather keep the README concise for that majority, with a link to a separate doc for the smaller audience of "developers of this repo". That's a pretty common approach - just as we have a separate CONTRIBUTING.md, for example.

I don't see that it's particularly difficult to replicate this setup across languages (or even have inconsistency between languages where appropriate).

**Comment by grant** [comment]
This is fine for now and we can refactor later if needed.
