### ISSUE TITLE
Should a nuget package be deprecated

### ISSUE THREAD

**Issue by thompson-tomo** [googleapis/google-cloudevents-dotnet#254]
Looking in Nuget.org, I came across Google.Events.SystemTextJson however it looks like it was never officially released

**Comment by jskeet** [comment]
Yes, we decided not to go ahead with that idea. The protobuf-based package is the only one we've taken forward.

**Comment by thompson-tomo** [comment]
@jskeet could you mark the mentioned Package as deprecated on nuget.org?

**Comment by jskeet** [comment]
Will delist them on Monday. Although I'd say in general that if you see a package where the only versions available are in alpha, the last release was over three years ago, and the source code has been deleted from the repo, it's probably a good signal that you shouldn't bet on it :)

**Comment by jskeet** [comment]
I've delisted and deprecated all versions now.
