### ISSUE TITLE
Use Google.CloudEvents Naming

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents-dotnet#26]
## Expected Behavior

Library name matches project scope and supports CloudEvent branding/tooling from Google.

## Actual Behavior

Currently use we `Google.Events`. Not sure why we're doing this as we definitely are building generators and are using properties for CloudEvent payloads.

**Comment by jskeet** [comment]
This comes back to an internal discussion we were going to have about whether the google-cloudevents repo was exclusively for CloudEvents, or potentially other event formats in the future. (That's why the protobuf package is `google.events.*`.)

I suggest we take that discussion back internally.

**Comment by grant** [comment]
I've tried to ping you on hangouts but I can't reach you. Happy to discuss internally.

**Comment by jskeet** [comment]
(Not online internally, but wanted to add this before I forgot again.) Just remembered one reason for preferring Google.Events - it doesn't sound like it's part of Google Cloud. I think if "Google Cloud" weren't a product, I'd be happier with Google.CloudEvents than I am at the moment.
