### ISSUE TITLE
Use GAPIC Generator instead of Protoc

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents-dotnet#28]
## Expected Behavior

Libraries should use the corresponding GAPIC generator instead of protoc for library generation for uniform libraries across languages.

https://github.com/googleapis/gapic-generator-csharp

## Actual Behavior

This repo does not use the GAPIC generator, it uses protoc directly:

https://github.com/googleapis/google-cloudevents-dotnet/blob/master/generate-code.sh#L81

**Comment by jskeet** [comment]
No, this is not appropriate. GAPIC generates *API clients*. There's no API here.

The DTO part of the C# client libraries is generated by protoc in exactly the same way as this repo is doing.
For some other languages, using GAPIC may be appropriate if it does something different with DTOs - but for C#, we're already doing the right thing here, so I'll close this issue.
