### ISSUE TITLE
How to use this cloudEvent in gRPC service contract proto?

### ISSUE THREAD

**Issue by JinsPeter** [googleapis/google-cloudevents-dotnet#29]
Apologies if this is not the right place to ask questions. Please direct me there and I will ask..

I am using gRPC communication with Duplex Streaming in .NET. I wrote a Service contract proto file. 
I want to follow CloudEvent specification for server streamed events. 
Is it possible to use this Google.Events.Protobuf - CloudEvent as the type of my message stream?
If possible, How to do that.?

**Comment by jskeet** [comment]
Currently we don't have a proto representing a general CloudEvent. This repository (and more broadly https://github.com/googleapis/google-cloudevents) is about the event data for specify Google events.

There is work going on in the CloudEvents spec around standardizing a protobuf representation of the overall CloudEvent - see https://github.com/cloudevents/spec/pull/626. I'll close this issue now as it's not the aim of this repo, but I think if you follow that Pull Request (and comment on it) that's probably what you're looking for.
