### ISSUE TITLE
Package Badges

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents-dotnet#53]
Idea: It would be cool to show the live version of the packages via a badge in the top of the README like is done for some other libraries.

`Google.Events`: [![Google.Events](https://img.shields.io/nuget/v/Google.Events.svg)](https://www.nuget.org/packages/Google.Events/) 
`Google.Events.Protobuf`: [![Google.Events.Protobuf](https://img.shields.io/nuget/v/Google.Events.Protobuf.svg)](https://www.nuget.org/packages/Google.Events.Protobuf/)

---

If we want, we could also add the # of downloads (probably not useful):

[![NuGet Download](https://img.shields.io/nuget/dt/Google.Events.svg?style=flat-square)](https://www.nuget.org/packages/Google.Events)

**Comment by jskeet** [comment]
Happy to do the version badges. Number of downloads is bizarrely meaningless as an actual number though. Will do this tomorrow.
